import Link from "next/link";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

const SAMPLE_REPORT = `## Executive Summary

The on-device AI market is projected to reach **$67.4 billion by 2027**, growing at a CAGR of 29.3% from 2023. Unlike cloud-based AI, on-device models run inference locally - eliminating latency, reducing costs, and addressing growing privacy concerns.

## Key Market Drivers

- **Privacy regulation**: GDPR and emerging US state laws are pushing enterprises toward local inference to avoid transmitting sensitive data.
- **Hardware maturity**: Apple\'s M-series chips and Qualcomm\'s Snapdragon X Elite now run 7B parameter models at production-grade speed.
- **Cost pressure**: At scale, cloud inference costs are 40-60x higher than equivalent on-device compute.

## Competitive Landscape

| Player | Approach | Key product |
|---|---|---|
| Apple | Vertical integration | Apple Intelligence / Core ML |
| Qualcomm | Silicon licensing | Snapdragon X Elite NPU |
| Google | Hybrid cloud/device | Gemini Nano |
| Microsoft | Edge deployment | Phi-3 Mini |

## Analyst Take

The winners in this space will be companies that solve the **model compression problem** - getting capable models below 4B parameters without meaningful quality degradation. Quantisation and distillation techniques are advancing rapidly; expect sub-2B models competitive with today\'s 7B models within 18 months.
`;

export default function ExampleReportSection(): JSX.Element {
  return (
    <section id="example-report" className="px-4 py-16 sm:px-6" aria-labelledby="example-report-heading">
      <div className="mx-auto w-full max-w-6xl text-center">
        <h2 id="example-report-heading" className="text-3xl font-semibold text-neutral-900">
          See what Studio produces
        </h2>
        <p className="mt-2 text-neutral-600">A real report generated by Studio in 73 seconds.</p>

        <div className="mx-auto mt-10 w-full max-w-3xl rounded-xl border border-neutral-200 bg-white p-6 text-left shadow-lg sm:p-8">
          <div className="prose prose-neutral max-w-none prose-headings:text-neutral-900 prose-p:text-neutral-700">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{SAMPLE_REPORT}</ReactMarkdown>
          </div>
        </div>

        <p className="mt-4 text-sm text-neutral-500">
          Generated in 73 seconds · 847 words · 9 sources · Market Analysis
        </p>

        <Link
          href="/auth/signup"
          className="mt-6 inline-flex items-center justify-center rounded-lg bg-indigo-600 px-6 py-3 text-base font-medium text-white transition hover:bg-indigo-700"
        >
          Generate a report like this -&gt;
        </Link>
      </div>
    </section>
  );
}
