import Link from "next/link";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Button } from "@/components/ui/Button";
import { FileText, Clock, BarChart, Database } from "lucide-react";

const SAMPLE_REPORT = `## Executive Summary

The on-device AI market is projected to reach **$67.4 billion by 2027**, growing at a CAGR of 29.3% from 2023. Unlike cloud-based AI, on-device models run inference locally - eliminating latency, reducing costs, and addressing growing privacy concerns.

## Key Market Drivers

- **Privacy regulation**: GDPR and emerging US state laws are pushing enterprises toward local inference to avoid transmitting sensitive data.
- **Hardware maturity**: Apple\'s M-series chips and Qualcomm\'s Snapdragon X Elite now run 7B parameter models at production-grade speed.
- **Cost pressure**: At scale, cloud inference costs are 40-60x higher than equivalent on-device compute.

## Competitive Landscape

| Player | Approach | Key product |
|---|---|---|
| Apple | Vertical integration | Apple Intelligence / Core ML |
| Qualcomm | Silicon licensing | Snapdragon X Elite NPU |
| Google | Hybrid cloud/device | Gemini Nano |
| Microsoft | Edge deployment | Phi-3 Mini |

## Analyst Take

The winners in this space will be companies that solve the **model compression problem** - getting capable models below 4B parameters without meaningful quality degradation. Quantisation and distillation techniques are advancing rapidly; expect sub-2B models competitive with today\'s 7B models within 18 months.
`;

export default function ExampleReportSection(): JSX.Element {
  return (
    <section id="example-report" className="px-6" aria-labelledby="example-report-heading">
      <div className="mx-auto w-full max-w-6xl text-center">
        <div className="animate-glass-enter">
          <span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/05 px-4 py-1.5 text-[11px] font-bold uppercase tracking-[0.2em] text-white/40 backdrop-blur-sm">
            LIVE OUTPUT
          </span>
          <h2 id="example-report-heading" className="mt-10 text-[38px] font-semibold tracking-tight text-white sm:text-[48px] leading-[1.1]">
            See what Studio produces
          </h2>
          <p className="mt-6 text-[17px] leading-relaxed text-[var(--text-secondary)] sm:text-[19px] max-w-2xl mx-auto font-light">
            A real report generated by Studio in 73 seconds. Professional, structured, and ready to ship.
          </p>
        </div>

        <div className="mx-auto mt-20 w-full max-w-4xl relative group">
          <div className="absolute -inset-8 rounded-[3rem] bg-white/[0.01] blur-3xl -z-10 group-hover:bg-white/[0.03] transition-all duration-700" />
          
          <div className="glass-card !bg-black/40 !p-0 overflow-hidden !rounded-[2rem] text-left border-white/10 shadow-2xl">
            {/* Browser Header */}
            <div className="border-b border-white/[0.08] bg-white/[0.05] px-8 py-5 flex items-center justify-between backdrop-blur-md">
              <div className="flex gap-2.5">
                <div className="h-3.5 w-3.5 rounded-full bg-white/10" />
                <div className="h-3.5 w-3.5 rounded-full bg-white/10" />
                <div className="h-3.5 w-3.5 rounded-full bg-white/10" />
              </div>
              <div className="text-[12px] font-mono text-white/40 uppercase tracking-[0.2em] font-medium">
                REPORT_PREVIEW.MD
              </div>
              <div className="w-12" />
            </div>
            
            <div className="p-10 md:p-14 max-h-[600px] overflow-y-auto custom-scrollbar">
              <div className="prose prose-zinc prose-report max-w-none prose-invert">
                <ReactMarkdown remarkPlugins={[remarkGfm]}>{SAMPLE_REPORT}</ReactMarkdown>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-16 flex flex-wrap items-center justify-center gap-10">
          <div className="flex items-center gap-3 text-[13px] font-bold uppercase tracking-[0.15em] text-white/40">
            <Clock className="h-5 w-5 text-white/20" />
            73 SECONDS
          </div>
          <div className="flex items-center gap-3 text-[13px] font-bold uppercase tracking-[0.15em] text-white/40">
            <BarChart className="h-5 w-5 text-white/20" />
            847 WORDS
          </div>
          <div className="flex items-center gap-3 text-[13px] font-bold uppercase tracking-[0.15em] text-white/40">
            <Database className="h-5 w-5 text-white/20" />
            9 SOURCES
          </div>
        </div>

        <Link href="/auth/signup" passHref legacyBehavior>
          <Button
            variant="primary"
            className="mt-16 !rounded-full !h-[60px] px-12 bg-white text-black font-bold hover:bg-white/90 transition-all hover:scale-[1.02]"
          >
            Generate a report like this
          </Button>
        </Link>
      </div>
    </section>
  );
}

